apiVersion: v1
kind: Service
metadata:
  name: mario-service   #This is service name
spec:
  type: LoadBalancer
  selector:
    app: mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
